language: python
python:
    - 3.6

install: "pip install unicodecsv"

script:
    - cd docs
    - python generate_report.py

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
